name: Daily Reddit Search

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7:00 UTC (9:00 Madrid time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  search:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install praw pushbullet.py google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
    - name: Run search script
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        PUSHBULLET_API_KEY: ${{ secrets.PUSHBULLET_API_KEY }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: python main.py
